# To use the common RDS database:
# databaseUrl: postgresql://postgres:...@goldilocks-dev4.c5pfza6ihb2z.us-east-1.rds.amazonaws.com:5432/postgres

# To use a PostgreSQL database on OS X (Homebrew):
# databaseUrl: postgresql://localhost:5432/goldie

# To use a PostgreSQL database on Fedora:
# databaseUrl: postgresql://postgres:postgres@localhost:5432/goldie

# This is optional. When you set up the AWS CLI for local development, it will
# create a profile, and store it in ~/.aws/credentials. This includes the
# aws_access_key_id and aws_secret_access_key of your IAM user. You can have
# multiple profiles stored in ~/.aws/credentials.  If you only have one
# profile, you do not need this variable - it will use the profile you set up
# as the default credentials for your AWS config.  If you have more than one
# profile set up (e.g. a personal AWS account, and an account for curvewise),
# then you can set the awsProfile config variable, and it will use the
# credentials in that profile for your AWS config. This is the same as
# using the --profile flag in the AWS CLI.
# For further information, see: https://aws.amazon.com/cli/
# awsProfile: goldilocks_data_layer

# This is the bucket that will be used for importing body mesh geometry into
# the goldilocks database.
# importBucket: goldilocks-upload

# To test authentication locally, generate a shared secret using
# node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"
# and uncomment this block.

# auth:
#   enabled: true
#   sharedSecret: '...'
